#ifdef QUANTUS_VERSION
#ifndef _GUI_QUANTUS_HOME_WIDGETS_H
#define _GUI_QUANTUS_HOME_WIDGETS_H

#define HOME_WIDGETS_SURPLUS_CARD_ENUM

#define HOME_WALLET_STATE_SURPLUS

#define HOME_WALLET_CARD_SURPLUS

#endif
#endif

