[package]
name = "app_quantus"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
hex = { workspace = true }
keystore = { workspace = true }
thiserror = { workspace = true }
app_utils = { workspace = true }
cryptoxide = { workspace = true }
bitcoin = { workspace = true }
qp-rusty-crystals-dilithium = "2.0.0"
qp-rusty-crystals-hdwallet = "1.0.0"
ss58 = { version = "0.0.3", default-features = false }
zeroize = { version = "1.8", features = ["derive"], default-features = false }
qp-poseidon = "1.0.1"
sp-core = { version = "37.0.0", default-features = false }

[dev-dependencies]
keystore = { path = "../../keystore" }
